# -*- coding: utf-8 -*-
import streamlit as st

st.title("Afibuy")
st.write("Welcome to Afibuy - Liberia Global Trade Intelligence Platform")
"""Afibuy_Liberia_Global_Trade_Intelligence1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtKi1AMMaic5v9Uroebdd8sjp5j_6zKr

# Afibuy Liberia Global Trade Intelligence Platform
Google Colab notebook template.
"""

!pip install streamlit pandas numpy plotly scikit-learn reportlab pyngrok

import pandas as pd
import numpy as np
import sqlite3
import random

### CREATE COUNTRIES LIST
source_countries = [
    "China",
    "India",
    "United States",
    "Germany",
    "Turkey",
    "Brazil",
    "Vietnam",
    "Netherlands",
    "Belgium",
    "Morocco",
    "Nigeria",
    "Ghana",
    "Senegal"
]

destination_country = "Liberia"

### PRODUCTS CATEGORIES
categories = {
    "Agriculture":[
        "Rice",
        "Palm Oil",
        "Cassava",
        "Cocoa",
        "Coffee"
    ],

    "Electronics":[
        "Smartphone",
        "Laptop",
        "Tablet",
        "Router",
        "Printer"
    ],

    "Construction":[
        "Cement",
        "Steel Rod",
        "Roofing Sheet",
        "Tiles",
        "Paint"
    ],

    "Automobile":[
        "Car Battery",
        "Brake Pad",
        "Engine Oil",
        "Tire",
        "Spark Plug"
    ],

    "Pharmaceutical":[
        "Paracetamol",
        "Antibiotics",
        "Vitamin C",
        "Malaria Kit",
        "Syringe"
    ]
}

### GENERATE 100000 PRODUCTS
rows = []

for i in range(100000):

    category = random.choice(
        list(categories.keys())
    )

    product = random.choice(
        categories[category]
    )

    import_cost = round(
        random.uniform(5,5000),
        2
    )

    selling_price = round(
        import_cost *
        random.uniform(1.15,2.50),
        2
    )

    profit = round(
        selling_price - import_cost,
        2
    )

    margin = round(
        (profit/import_cost)*100,
        2
    )

    rows.append([
        i+1,
        product,
        category,
        random.choice(source_countries),
        destination_country,
        import_cost,
        selling_price,
        profit,
        margin
    ])

### CREATE DATAFRAME
df = pd.DataFrame(
    rows,
    columns=[
        "ProductID",
        "ProductName",
        "Category",
        "SourceCountry",
        "DestinationCountry",
        "ImportCostUSD",
        "SellingPriceUSD",
        "ProfitUSD",
        "ProfitMargin"
    ]
)

df.head()

### SAVE DATASETS
df.to_csv(
    "Liberia_Global_Trade_100K.csv",
    index=False
)

print(
    "100,000 product dataset created successfully."
)

### VERIFY DATASETS
print(df.shape)

### ADD DEMAND SCORE, RISK LEVEL, OPPORTUNITY SCORE, HS CODES & SUPPLIERS
import random

supplier_names = [
    "Liberia Trade Hub",
    "Monrovia Imports",
    "Global Trade Africa",
    "West Africa Commerce",
    "Prime Suppliers Ltd",
    "Atlantic Trading Group",
    "Ocean Gate Imports",
    "Liberty Logistics",
    "Freeport Trading",
    "World Commerce Inc"
]

ports = [
    "Freeport of Monrovia",
    "Buchanan Port",
    "Greenville Port",
    "Harper Port"
]

hs_codes = []

demand_scores = []

risk_levels = []

opportunity_scores = []

suppliers = []

port_list = []

for _, row in df.iterrows():

    hs_codes.append(
        random.randint(100000,999999)
    )

    demand = random.randint(50,100)

    demand_scores.append(demand)

    if row["ProfitMargin"] >= 50:
        risk = "Low Risk"

    elif row["ProfitMargin"] >= 25:
        risk = "Medium Risk"

    else:
        risk = "High Risk"

    risk_levels.append(risk)

    score = (
        demand +
        min(int(row["ProfitMargin"]),100)
    ) // 2

    opportunity_scores.append(score)

    suppliers.append(
        random.choice(supplier_names)
    )

    port_list.append(
        random.choice(ports)
    )

df["HSCode"] = hs_codes

df["DemandScore"] = demand_scores

df["RiskLevel"] = risk_levels

df["OpportunityScore"] = opportunity_scores

df["SupplierName"] = suppliers

df["Port"] = port_list

df.head()

print(df.columns.tolist())

### SAVE AND ENHANCED
df.to_csv(
    "Liberia_Global_Trade_100K_Enhanced.csv",
    index=False
)

print("Enhanced dataset saved.")

### LOAD INTO SQLITE
import sqlite3

conn = sqlite3.connect(
    "afibuy_database.db"
)

df.to_sql(
    "liberia_trade_data",
    conn,
    if_exists="replace",
    index=False
)

conn.commit()

print(
    "100,000 records loaded into SQLite."
)

query = """
SELECT COUNT(*)
FROM liberia_trade_data
"""

import pandas as pd

pd.read_sql(
    query,
    conn
)

### DATABOARD INTEGRATION
top_products = (
    df.groupby("ProductName")
      ["ProfitUSD"]
      .sum()
      .sort_values(
          ascending=False
      )
      .head(20)
)

top_products

df = pd.read_csv(
    "Liberia_Global_Trade_100K_Enhanced.csv"
)

### REPLACE
# ==================================================
# LOAD LIBERIA TRADE DATABASE
# ==================================================

import sqlite3

conn = sqlite3.connect(
    "afibuy_database.db"
)

query = """
SELECT *
FROM liberia_trade_data
"""

df = pd.read_sql(
    query,
    conn
)

print(df.shape)

import streamlit as st

### LIBERIA KPI DASHBOARD
st.subheader("🇱🇷 Liberia Trade Overview")

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Products",
        f"{len(df):,}"
    )

with col2:
    st.metric(
        "Total Profit",
        f"${df['ProfitUSD'].sum():,.0f}"
    )

with col3:
    st.metric(
        "Average Margin",
        f"{df['ProfitMargin'].mean():.2f}%"
    )

with col4:
    st.metric(
        "Suppliers",
        df['SupplierName'].nunique()
    )

import plotly.express as px

### TOP IMPORT COUNTRIES CHARTS
st.subheader(
    "🌍 Top Countries Exporting To Liberia"
)

country_df = (
    df.groupby("SourceCountry")
      .size()
      .reset_index(name="Products")
)

fig = px.bar(
    country_df,
    x="SourceCountry",
    y="Products",
    title="Imports Into Liberia"
)

st.plotly_chart(
    fig,
    width='stretch'
)

### PORT ANALYTICS
st.subheader(
    "🚢 Liberia Port Analytics"
)

port_df = (
    df.groupby("Port")
      .size()
      .reset_index(name="Volume")
)

fig = px.pie(
    port_df,
    names="Port",
    values="Volume",
    title="Trade Volume By Port"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

min_score = st.sidebar.slider(
    "Minimum Opportunity Score",
    0,
    100,
    70
)

opportunities = df[
    df["OpportunityScore"] >= min_score
]

st.subheader(
    "🔥 High Opportunity Products"
)

st.dataframe(
    opportunities[
        [
            "ProductName",
            "SourceCountry",
            "ProfitUSD",
            "OpportunityScore",
            "SupplierName"
        ]
    ].head(100)
)

### LIBERIA TRADE INTELIGENCE
liberia_exports = [
    "Rubber",
    "Iron Ore",
    "Gold",
    "Diamonds",
    "Palm Oil",
    "Cocoa",
    "Coffee",
    "Timber",
    "Cassava",
    "Fish"
]

export_rows = []

for i in range(50000):

    product = random.choice(
        liberia_exports
    )

    destination = random.choice([
        "China",
        "United States",
        "Germany",
        "Belgium",
        "India",
        "Morocco",
        "Turkey"
    ])

    export_value = round(
        random.uniform(1000,100000),
        2
    )

    export_rows.append([
        i + 1,
        product,
        "Liberia",
        destination,
        export_value
    ])

exports_df = pd.DataFrame(
    export_rows,
    columns=[
        "ExportID",
        "Product",
        "Origin",
        "Destination",
        "ExportValueUSD"
    ]
)

exports_df.head()

exports_df.to_sql(
    "liberia_exports",
    conn,
    if_exists="replace",
    index=False
)

conn.commit()

print(
    "Liberia exports loaded."
)

### TOP LIBERIAN EXPORTS
top_exports = (
    exports_df.groupby("Product")
    ["ExportValueUSD"]
    .sum()
    .sort_values(
        ascending=False
    )
)

top_exports

"Export Intelligence"

"""### Consolidated Streamlit App Structure

This cell demonstrates how all the individual Streamlit components from the previous cells would typically be combined into a single Python script for a Streamlit application. It uses `st.sidebar.selectbox` for navigation and `if-elif-else` statements to display different sections of the dashboard.
"""

import streamlit as st
import plotly.express as px

# Streamlit page configuration (optional, but good practice for full apps)
st.set_page_config(layout="wide", page_title="Liberia Global Trade Dashboard")

# Sidebar for navigation
st.sidebar.title("Navigation")
menu = st.sidebar.selectbox(
    "Choose a section",
    [
        "Liberia Trade Overview",
        "Top Countries Exporting To Liberia",
        "Liberia Port Analytics",
        "High Opportunity Products",
        "Export Intelligence"
    ]
)

# Content based on menu selection
if menu == "Liberia Trade Overview":
    ### LIBERIA KPI DASHBOARD
    st.subheader("🇱🇷 Liberia Trade Overview")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Products",
            f"{len(df):,}"
        )

    with col2:
        st.metric(
            "Total Profit",
            f"${df['ProfitUSD'].sum():,.0f}"
        )

    with col3:
        st.metric(
            "Average Margin",
            f"{df['ProfitMargin'].mean():.2f}%"
        )

    with col4:
        st.metric(
            "Suppliers",
            df['SupplierName'].nunique()
        )

elif menu == "Top Countries Exporting To Liberia":
    ### TOP IMPORT COUNTRIES CHARTS
    st.subheader(
        "🌍 Top Countries Exporting To Liberia"
    )

    country_df = (
        df.groupby("SourceCountry")
          .size()
          .reset_index(name="Products")
    )

    fig = px.bar(
        country_df,
        x="SourceCountry",
        y="Products",
        title="Imports Into Liberia"
    )

    st.plotly_chart(
        fig,
        width='stretch'
    )

elif menu == "Liberia Port Analytics":
    ### PORT ANALYTICS
    st.subheader(
        "🚢 Liberia Port Analytics"
    )

    port_df = (
        df.groupby("Port")
          .size()
          .reset_index(name="Volume")
    )

    fig = px.pie(
        port_df,
        names="Port",
        values="Volume",
        title="Trade Volume By Port"
    )

    st.plotly_chart(
        fig,
        width='stretch'
    )

elif menu == "High Opportunity Products":
    # Note: st.sidebar.slider in the original cell will render in the sidebar
    # alongside the navigation selectbox.
    min_score = st.sidebar.slider(
        "Minimum Opportunity Score",
        0,
        100,
        70
    )

    opportunities = df[
        df["OpportunityScore"] >= min_score
    ]

    st.subheader(
        "🔥 High Opportunity Products"
    )

    st.dataframe(
        opportunities[
            [
                "ProductName",
                "SourceCountry",
                "ProfitUSD",
                "OpportunityScore",
                "SupplierName"
            ]
        ].head(100)
    )

elif menu == "Export Intelligence":
    st.header(
        "🇱🇷 Liberia Export Intelligence"
    )

    export_summary = (
        exports_df.groupby("Product")
        ["ExportValueUSD"]
        .sum()
        .reset_index()
    )

    fig = px.bar(
        export_summary,
        x="Product",
        y="ExportValueUSD",
        title="Top Liberian Exports"
    )

    st.plotly_chart(
        fig,
        width='stretch'
    )

st.subheader(
    "💱 Currency Converter"
)

usd = st.number_input(
    "USD",
    value=100.0
)

lrd_rate = 198
mad_rate = 9.2

st.metric(
    "Liberian Dollars",
    f"{usd*lrd_rate:,.2f}"
)

st.metric(
    "Moroccan Dirham",
    f"{usd*mad_rate:,.2f}"
)

### create the streamlit link for the website:
!streamlit run app.py & npx localtunnel --port 8501

"""First, let's write the Streamlit application code into a Python file named `app.py`."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import plotly.express as px
# import sqlite3
# import pandas as pd
# import os
# 
# # Use st.cache_resource for database connection to ensure it's created once
# @st.cache_resource
# def get_db_connection():
#     conn = sqlite3.connect('afibuy.db')
#     # Optionally, set row_factory for easier access to columns by name
#     # conn.row_factory = sqlite3.Row
#     return conn
# 
# conn = get_db_connection()
# cursor = conn.cursor()
# 
# # Use st.cache_data for loading DataFrames to prevent repeated loading
# @st.cache_data
# def load_trade_data(_connection):
#     query_df = "SELECT * FROM trade_data"
#     return pd.read_sql(query_df, _connection)
# 
# @st.cache_data
# def load_exports_data(_connection):
#     query_exports_df = "SELECT * FROM exports_data"
#     return pd.read_sql(query_exports_df, _connection)
# 
# df = load_trade_data(conn)
# exports_df = load_exports_data(conn)
# 
# # Streamlit page configuration (optional, but good practice for full apps)
# st.set_page_config(layout="wide", page_title="Liberia Global Trade Dashboard")
# 
# # Sidebar for navigation
# st.sidebar.title("Navigation")
# menu = st.sidebar.selectbox(
#     "Choose a section",
#     [
#         "Liberia Trade Overview",
#         "Top Countries Exporting To Liberia",
#         "Liberia Port Analytics",
#         "High Opportunity Products",
#         "Export Intelligence",
#         "Currency Converter",
#         "Add Product",
#         "Marketplace"
#     ]
# )
# 
# # Content based on menu selection
# if menu == "Liberia Trade Overview":
#     ### LIBERIA KPI DASHBOARD
#     st.subheader("🇱🇷 Liberia Trade Overview")
# 
#     col1, col2, col3, col4 = st.columns(4)
# 
#     with col1:
#         st.metric(
#             "Products",
#             f"{len(df):,}"
#         )
# 
#     with col2:
#         st.metric(
#             "Total Profit",
#             f"${df['ProfitUSD'].sum():,.0f}"
#         )
# 
#     with col3:
#         st.metric(
#             "Average Margin",
#             f"{df['ProfitMargin'].mean():.2f}%"
#         )
# 
#     with col4:
#         st.metric(
#             "Suppliers",
#             df['SupplierName'].nunique()
#         )
# 
# elif menu == "Top Countries Exporting To Liberia":
#     ### TOP IMPORT COUNTRIES CHARTS
#     st.subheader(
#         "🌍 Top Countries Exporting To Liberia"
#     )
# 
#     country_df = (
#         df.groupby("SourceCountry")
#           .size()
#           .reset_index(name="Products")
#     )
# 
#     fig = px.bar(
#         country_df,
#         x="SourceCountry",
#         y="Products",
#         title="Imports Into Liberia"
#     )
# 
#     st.plotly_chart(
#         fig,
#         width='stretch'
#     )
# 
# elif menu == "Liberia Port Analytics":
#     ### PORT ANALYTICS
#     st.subheader(
#         "🚢 Liberia Port Analytics"
#     )
# 
#     port_df = (
#         df.groupby("Port")
#           .size()
#           .reset_index(name="Volume")
#     )
# 
#     fig = px.pie(
#         port_df,
#         names="Port",
#         values="Volume",
#         title="Trade Volume By Port"
#     )
# 
#     st.plotly_chart(
#         fig,
#         width='stretch'
#     )
# 
# elif menu == "High Opportunity Products":
#     # Note: st.sidebar.slider in the original cell will render in the sidebar
#     # alongside the navigation selectbox.
#     min_score = st.sidebar.slider(
#         "Minimum Opportunity Score",
#         0,
#         100,
#         70
#     )
# 
#     opportunities = df[
#         df["OpportunityScore"] >= min_score
#     ]
# 
#     st.subheader(
#         "🔥 High Opportunity Products"
#     )
# 
#     st.dataframe(
#         opportunities[
#             [
#                 "ProductName",
#                 "SourceCountry",
#                 "ProfitUSD",
#                 "OpportunityScore",
#                 "SupplierName"
#             ]
#         ].head(100)
#     )
# 
# elif menu == "Export Intelligence":
#     st.header(
#         "🇱🇷 Liberia Export Intelligence"
#     )
# 
#     export_summary = (
#         exports_df.groupby("Product")
#         ["ExportValueUSD"]
#         .sum()
#         .reset_index()
#     )
# 
#     fig = px.bar(
#         export_summary,
#         x="Product",
#         y="ExportValueUSD",
#         title="Top Liberian Exports"
#     )
# 
#     st.plotly_chart(
#         fig,
#         width='stretch'
#     )
# 
# elif menu == "Currency Converter":
#     st.subheader(
#         "💱 Currency Converter"
#     )
# 
#     usd = st.number_input(
#         "USD",
#         value=100.0
#     )
# 
#     lrd_rate = 198
#     mad_rate = 9.2
# 
#     st.metric(
#         "Liberian Dollars",
#         f"{usd*lrd_rate:,.2f}"
#     )
# 
#     st.metric(
#         "Moroccan Dirham",
#         f"{usd*mad_rate:,.2f}"
#     )
# 
# elif menu == "Add Product":
#     ### PRODUCT PAGE
# 
#     st.title("Add Product")
# 
#     product_name = st.text_input("Product Name")
# 
#     category = st.selectbox(
#         "Category",
#         [
#             "Agriculture",
#             "Fashion",
#             "Electronics",
#             "Beauty",
#             "Books",
#             "Home",
#             "Automobile"
#         ]
#     )
# 
#     price = st.number_input("Price", min_value=0.0)
# 
#     description = st.text_area("Description")
# 
#     image = st.file_uploader(
#         "Upload Product Image",
#         type=["jpg","jpeg","png"]
#     )
# 
#     if st.button("Add Product"):
# 
#         image_path = ""
# 
#         if image:
# 
#             # Create product_images directory if it doesn't exist
#             if not os.path.exists("product_images"):
#                 os.makedirs("product_images")
# 
#             image_path = os.path.join(
#                 "product_images",
#                 image.name
#             )
# 
#             with open(image_path, "wb") as f:
#                 f.write(image.getbuffer())
# 
#         # Assuming a default seller email or using st.session_state.email if set elsewhere
#         # For this example, we'll use a placeholder if st.session_state.email is not defined
#         seller_email = st.session_state.get('email', 'default_seller@example.com')
# 
#         cursor.execute(
#             """
#             INSERT INTO products(
#             seller_email,
#             product_name,
#             category,
#             price,
#             description,
#             image
#             )
#             VALUES(?,?,?,?,?,?)
#             """,
#             (
#                 seller_email,
#                 product_name,
#                 category,
#                 price,
#                 description,
#                 image_path
#             )
#         )
# 
#         conn.commit()
# 
#         st.success("Product Added Successfully")
# 
# elif menu == "Marketplace":
#     ### MARKETPLACE PAGE
#     st.title("Marketplace")
# 
#     search = st.text_input("Search Product")
# 
#     selected_category = st.selectbox(
#         "Filter Category",
#         [
#             "All",
#             "Agriculture",
#             "Fashion",
#             "Electronics",
#             "Beauty",
#             "Books",
#             "Home",
#             "Automobile"
#         ]
#     )
# 
#     query = "SELECT * FROM products"
#     # Re-fetch products from the database in case new ones were added
#     products = cursor.execute(query).fetchall()
# 
#     for product in products:
# 
#         product_name = product[2]
#         category = product[3]
#         price = product[4]
#         description = product[5]
#         image = product[6]
# 
#         # Apply search and category filters
#         if search.lower() not in product_name.lower():
#             continue
# 
#         if selected_category != "All":
# 
#             if category != selected_category:
#                 continue
# 
#         st.markdown("---")
# 
#         col1, col2 = st.columns([1,2])
# 
#         with col1:
# 
#             if image and os.path.exists(image):
#                 st.image(image,width=200)
# 
#         with col2:
# 
#             st.subheader(product_name)
# 
#             st.write("Category:",category)
# 
#             st.write("Price: $",price)
# 
#             st.write(description)
# 
#             st.write("Seller:",product[1])

"""Now, let's run the Streamlit app and expose it using `ngrok`. You'll need an `NGROK_AUTH_TOKEN`. If you don't have one, get it from [ngrok dashboard](https://dashboard.ngrok.com/get-started/your-authtoken). Add it to the Colab secrets manager under the "🔑" in the left panel, named `NGROK_AUTH_TOKEN`."""

import subprocess
import threading
import time
import os
import socket
from pyngrok import ngrok, conf
from google.colab import userdata

# Kill any running Streamlit processes
subprocess.run(["killall", "-9", "streamlit"], capture_output=True, text=True, check=False) # Added check=False

# Get ngrok auth token from Colab secrets, or use existing if already set
NGROK_AUTH_TOKEN = None
if 'NGROK_AUTH_TOKEN' in locals() and locals()['NGROK_AUTH_TOKEN'] is not None:
    NGROK_AUTH_TOKEN = locals()['NGROK_AUTH_TOKEN']
elif 'NGROK_AUTH_TOKEN' in globals() and globals()['NGROK_AUTH_TOKEN'] is not None:
    NGROK_AUTH_TOKEN = globals()['NGROK_AUTH_TOKEN']
else:
    try:
        NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')
    except Exception as e:
        print(f"Could not retrieve NGROK_AUTH_TOKEN from secrets: {e}")

# Set ngrok auth token
if NGROK_AUTH_TOKEN:
    conf.get_default().auth_token = NGROK_AUTH_TOKEN
else:
    print("NGROK_AUTH_TOKEN not found or set. Please add it to Colab secrets.")

streamlit_log_file = "streamlit_output.log"

# Run Streamlit in a separate thread
def run_streamlit():
    try:
        os.chmod('app.py', 0o755)
        # Redirect stdout and stderr to a file for debugging
        with open(streamlit_log_file, "w") as f:
            subprocess.Popen([
                "streamlit", "run", "app.py",
                "--server.port", "8501",
                "--server.address", "0.0.0.0",
                "--browser.gatherUsageStats", "False"
            ], stdout=f, stderr=subprocess.STDOUT, preexec_fn=os.setsid) # preexec_fn for detaching process group
        print(f"Streamlit process started in background. Output redirected to '{streamlit_log_file}'.")
    except Exception as e:
        print(f"Error starting Streamlit process: {e}")

streamlit_thread = threading.Thread(target=run_streamlit)
streamlit_thread.start()

# Function to check if a port is open
def is_port_open(host, port, timeout=1):
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except (socket.timeout, ConnectionRefusedError, OSError):
        return False

# Wait for Streamlit to start and its port to be open
start_time = time.time()
timeout = 90 # seconds (increased timeout for robustness)
streamlit_ready = False
STREAMLIT_PORT = 8501
STREAMLIT_HOST = "127.0.0.1"

print(f"Waiting for Streamlit server to be ready on {STREAMLIT_HOST}:{STREAMLIT_PORT}...")
while not streamlit_ready and (time.time() - start_time < timeout):
    if is_port_open(STREAMLIT_HOST, STREAMLIT_PORT):
        streamlit_ready = True
        print(f"Streamlit server detected as ready on {STREAMLIT_HOST}:{STREAMLIT_PORT}.")
    else:
        print(f"Port {STREAMLIT_PORT} not yet open. Waiting...")
    time.sleep(5) # Check every 5 seconds

if not streamlit_ready:
    print(f"Streamlit did not become ready on {STREAMLIT_HOST}:{STREAMLIT_PORT} within {timeout} seconds. Check '{streamlit_log_file}' for errors.")
    # Optionally, print log content if Streamlit didn't start
    if os.path.exists(streamlit_log_file):
        with open(streamlit_log_file, "r") as f:
            print("--- Streamlit log content (if available) ---")
            print(f.read())
            print("---------------------------------------------")

# Setup ngrok tunnel only if Streamlit is ready
if streamlit_ready:
    try:
        # Disconnect any existing tunnels
        ngrok.kill()

        # Create a new tunnel to port 8501, explicitly targeting IPv4 localhost
        public_url = ngrok.connect(addr=f"{STREAMLIT_HOST}:{STREAMLIT_PORT}", proto="http")
        print(f"Streamlit app available at: {public_url}")
    except Exception as e:
        print(f"Error setting up ngrok tunnel: {e}")
        ngrok.kill()
        # If ngrok failed, print the Streamlit log to help debug
        print(f"Checking Streamlit output log ('{streamlit_log_file}') for errors:")
        if os.path.exists(streamlit_log_file):
            with open(streamlit_log_file, "r") as f:
                print(f.read())
        else:
            print("Streamlit log file not found.")
else:
    print("ngrok tunnel not started because Streamlit failed to launch or become ready.")

# Read and print the content of the Streamlit log file to diagnose issues
streamlit_log_file = "streamlit_output.log"

print(f"--- Content of {streamlit_log_file} ---")
if os.path.exists(streamlit_log_file):
    with open(streamlit_log_file, "r") as f:
        log_content = f.read()
        if log_content:
            print(log_content)
        else:
            print(f"The log file '{streamlit_log_file}' is empty.")
else:
    print(f"The log file '{streamlit_log_file}' does not exist.")
print(f"--- End of {streamlit_log_file} ---")

# Read and print the content of the Streamlit log file to diagnose issues
streamlit_log_file = "streamlit_output.log"

print(f"--- Content of {streamlit_log_file} ---")
if os.path.exists(streamlit_log_file):
    with open(streamlit_log_file, "r") as f:
        log_content = f.read()
        if log_content:
            print(log_content)
        else:
            print(f"The log file '{streamlit_log_file}' is empty.")
else:
    print(f"The log file '{streamlit_log_file}' does not exist.")
print(f"--- End of {streamlit_log_file} ---")

### NEW DATABASE SCHEMA
import sqlite3

def create_database():

    conn = sqlite3.connect("afibuy.db")
    cursor = conn.cursor()

    # Users

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        fullname TEXT,
        email TEXT UNIQUE,
        password TEXT,
        role TEXT
    )
    """)

    # Products

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS products(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        seller_email TEXT,
        product_name TEXT,
        category TEXT,
        price REAL,
        description TEXT,
        image TEXT
    )
    """)

    conn.commit()
    conn.close()

create_database()

"""### Migrate Existing Trade Data to `afibuy.db`

Now that `afibuy.db` has been created, we will move the existing `liberia_trade_data` (currently in `df`) and `liberia_exports` (currently in `exports_df`) into this new database. We'll store them as `trade_data` and `exports_data` tables within `afibuy.db`.
"""

import sqlite3

# Connect to the new database
conn_new_db = sqlite3.connect('afibuy.db')

# Save the main trade data (df) into a new table 'trade_data' in afibuy.db
df.to_sql(
    "trade_data",
    conn_new_db,
    if_exists="replace",
    index=False
)

# Save the exports data (exports_df) into a new table 'exports_data' in afibuy.db
exports_df.to_sql(
    "exports_data",
    conn_new_db,
    if_exists="replace",
    index=False
)

conn_new_db.commit()
conn_new_db.close()

print("Trade data and exports data successfully migrated to 'afibuy.db'.")

import os

if not os.path.exists("product_images"):
    os.makedirs("product_images")

print("Folder Created")

### PRODUCT PAGE
import os

st.title("Add Product")

product_name = st.text_input("Product Name")

category = st.selectbox(
    "Category",
    [
        "Agriculture",
        "Fashion",
        "Electronics",
        "Beauty",
        "Books",
        "Home",
        "Automobile"
    ]
)

price = st.number_input("Price", min_value=0.0)

description = st.text_area("Description")

image = st.file_uploader(
    "Upload Product Image",
    type=["jpg","jpeg","png"]
)

if st.button("Add Product"):

    image_path = ""

    if image:

        image_path = os.path.join(
            "product_images",
            image.name
        )

        with open(image_path, "wb") as f:
            f.write(image.getbuffer())

    cursor.execute(
        """
        INSERT INTO products(
        seller_email,
        product_name,
        category,
        price,
        description,
        image
        )
        VALUES(?,?,?,?,?,?)
        """,
        (
            st.session_state.email,
            product_name,
            category,
            price,
            description,
            image_path
        )
    )

    conn.commit()

    st.success("Product Added Successfully")

import sqlite3

conn = sqlite3.connect("afibuy.db")
cursor = conn.cursor()

sample_products = [

("seller1@gmail.com","Coffee Beans","Agriculture",25,"Premium Liberian coffee",""),

("seller2@gmail.com","African Fabric","Fashion",50,"Traditional fabric",""),

("seller3@gmail.com","Laptop","Electronics",700,"Dell laptop",""),

("seller4@gmail.com","Organic Honey","Agriculture",15,"Pure honey","")

]

cursor.executemany(
"""
INSERT INTO products(
seller_email,
product_name,
category,
price,
description,
image
)
VALUES(?,?,?,?,?,?)
""",
sample_products
)

conn.commit()
conn.close()

import sqlite3

# Re-establish connection to afibuy.db
conn = sqlite3.connect("afibuy.db")
cursor = conn.cursor()

# Cart Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS cart(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    buyer_email TEXT,
    product_id INTEGER,
    quantity INTEGER
)
""")

# Orders Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS orders(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    buyer_email TEXT,
    total REAL,
    status TEXT
)
""")

# Order Items
cursor.execute("""
CREATE TABLE IF NOT EXISTS order_items(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    price REAL
)
""")

conn.commit()
conn.close()

"""### Replacing the Database: Re-creating and Populating `afibuy.db`"""

import sqlite3

def create_and_populate_database():
    conn = sqlite3.connect("afibuy.db")
    cursor = conn.cursor()

    # Drop tables if they exist to ensure a fresh start
    cursor.execute("DROP TABLE IF EXISTS users")
    cursor.execute("DROP TABLE IF EXISTS products")
    cursor.execute("DROP TABLE IF EXISTS cart")
    cursor.execute("DROP TABLE IF EXISTS orders")
    cursor.execute("DROP TABLE IF EXISTS order_items")
    cursor.execute("DROP TABLE IF EXISTS trade_data")
    cursor.execute("DROP TABLE IF EXISTS exports_data")

    # Users Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        fullname TEXT,
        email TEXT UNIQUE,
        password TEXT,
        role TEXT
    )
    """)

    # Products Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS products(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        seller_email TEXT,
        product_name TEXT,
        category TEXT,
        price REAL,
        description TEXT,
        image TEXT
    )
    """)

    # Cart Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS cart(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        buyer_email TEXT,
        product_id INTEGER,
        quantity INTEGER
    )
    """)

    # Orders Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS orders(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        buyer_email TEXT,
        total REAL,
        status TEXT
    )
    """)

    # Order Items Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS order_items(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id INTEGER,
        product_id INTEGER,
        quantity INTEGER,
        price REAL
    )
    """)

    # Migrate existing trade data (df) into 'trade_data' table
    # Assuming 'df' and 'exports_df' DataFrames are already in memory from previous steps.
    # If not, you might need to load them first.
    if 'df' in globals():
        df.to_sql(
            "trade_data",
            conn,
            if_exists="replace",
            index=False
        )
    else:
        print("Warning: 'df' DataFrame not found. Trade data not migrated.")

    # Migrate existing exports data (exports_df) into 'exports_data' table
    if 'exports_df' in globals():
        exports_df.to_sql(
            "exports_data",
            conn,
            if_exists="replace",
            index=False
        )
    else:
        print("Warning: 'exports_df' DataFrame not found. Exports data not migrated.")

    # Add sample products
    sample_products = [
        ("seller1@gmail.com","Coffee Beans","Agriculture",25,"Premium Liberian coffee",""),
        ("seller2@gmail.com","African Fabric","Fashion",50,"Traditional fabric",""),
        ("seller3@gmail.com","Laptop","Electronics",700,"Dell laptop",""),
        ("seller4@gmail.com","Organic Honey","Agriculture",15,"Pure honey","")
    ]

    cursor.executemany(
    """
    INSERT INTO products(
    seller_email,
    product_name,
    category,
    price,
    description,
    image
    )
    VALUES(?,?,?,?,?,?)
    """,
    sample_products
    )

    conn.commit()
    conn.close()
    print("Database 'afibuy.db' recreated, schema applied, and data populated successfully.")

create_and_populate_database()



